name: Deploy

on:
  release:
    types: [published]
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  vercel:
    runs-on: ubuntu-latest
    name: Deploy front-end
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2 # updated to use latest version of setup-node
        with:
          node-version: '16' # updated to use a more specific version of Node.js
          registry-url: https://registry.npmjs.org/

      - name: Deploy to Vercel
        run: |
          prodRun=""
          if [[ ${{ github.ref }} == "refs/heads/main" ]]; then # updated to use github context instead of environment variable
            prodRun="--prod"
          fi

          npx vercel --token ${{ secrets.VERCEL_TOKEN }} $prodRun
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
